import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { TemplateEngine } from "recker";

const ROOT = resolve(import.meta.dirname, "..");
const PROMPTS_DIR = join(ROOT, "src", "agents", "prompts");
const OUTPUT_DIR = join(ROOT, "src", "agents", "generated");
const OUTPUT_FILE = join(OUTPUT_DIR, "prompts.ts");
const FIXTURES_DIR = join(ROOT, "src", "agents", "fixtures");

const engine = new TemplateEngine();

type PromptRecord = {
  name: string;
  sourcePath: string;
  template: string;
};

type CatalogEntry = Record<string, unknown> & {
  stub?: string;
};

type CatalogManifest = {
  fixtureFilename: string;
  manifestFilename: string;
};

const CATALOG_MANIFESTS: CatalogManifest[] = [
  { fixtureFilename: "agent-catalog.json", manifestFilename: "agent-catalog.manifest.json" },
  { fixtureFilename: "skill-catalog.json", manifestFilename: "skill-catalog.manifest.json" },
];

function loadTemplate(sourcePath: string): string {
  const template = readFileSync(sourcePath, "utf8");
  const validation = engine.validate(template);
  if (!validation.valid) {
    const details = validation.errors
      .map((error) => `${error.message} (${error.line}:${error.column})`)
      .join("; ");
    throw new Error(`Invalid prompt stub ${relative(ROOT, sourcePath)}: ${details}`);
  }
  return template;
}

function loadCatalogStubNames(): Set<string> {
  const stubNames = new Set<string>();

  for (const manifest of CATALOG_MANIFESTS) {
    const manifestPath = join(PROMPTS_DIR, manifest.manifestFilename);
    const entries = JSON.parse(readFileSync(manifestPath, "utf8")) as CatalogEntry[];
    for (const entry of entries) {
      if (typeof entry.stub === "string" && entry.stub.trim()) {
        stubNames.add(entry.stub.trim());
      }
    }
  }

  return stubNames;
}

function loadPromptRecords(excludedStubNames: Set<string>): PromptRecord[] {
  return readdirSync(PROMPTS_DIR, { withFileTypes: true })
    .filter((entry) =>
      entry.isFile()
      && entry.name.endsWith(".stub.md")
      && !excludedStubNames.has(entry.name)
    )
    .map((entry) => {
      const sourcePath = join(PROMPTS_DIR, entry.name);
      return {
        name: entry.name.replace(/\.stub\.md$/u, ""),
        sourcePath,
        template: loadTemplate(sourcePath),
      };
    })
    .sort((left, right) => left.name.localeCompare(right.name));
}

function buildOutput(records: PromptRecord[]): string {
  const entries = records
    .map((record) => {
      const relPath = relative(ROOT, record.sourcePath).replace(/\\/g, "/");
      return `  ${JSON.stringify(record.name)}: ${JSON.stringify(record.template)}, // ${relPath}`;
    })
    .join("\n");

  return [
    "// Generated by scripts/generate-prompts.ts. Do not edit directly.",
    "",
    "export const PROMPT_TEMPLATES = {",
    entries,
    "} as const;",
    "",
    "export type PromptTemplateName = keyof typeof PROMPT_TEMPLATES;",
    "",
  ].join("\n");
}

function generateCatalogFixtures(): Set<string> {
  const stubNames = new Set<string>();

  for (const manifest of CATALOG_MANIFESTS) {
    const manifestPath = join(PROMPTS_DIR, manifest.manifestFilename);
    const entries = JSON.parse(readFileSync(manifestPath, "utf8")) as CatalogEntry[];
    const fixtureEntries = entries.map((entry) => {
      if (typeof entry.stub !== "string" || !entry.stub.trim()) {
        return entry;
      }

      const stub = entry.stub.trim();
      stubNames.add(stub);
      const sourcePath = join(PROMPTS_DIR, stub);
      const content = loadTemplate(sourcePath);
      const { stub: _stub, ...rest } = entry;
      return { ...rest, content };
    });

    writeFileSync(
      join(FIXTURES_DIR, manifest.fixtureFilename),
      `${JSON.stringify(fixtureEntries, null, 2)}\n`,
      "utf8",
    );
  }

  return stubNames;
}

function main(): void {
  const catalogStubNames = generateCatalogFixtures();
  const records = loadPromptRecords(catalogStubNames);
  mkdirSync(OUTPUT_DIR, { recursive: true });
  writeFileSync(OUTPUT_FILE, buildOutput(records), "utf8");
}

main();
