import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { TemplateEngine } from "recker";

const ROOT = resolve(import.meta.dirname, "..");
const PROMPTS_DIR = join(ROOT, "src", "agents", "prompts");
const OUTPUT_DIR = join(ROOT, "src", "agents", "generated");
const OUTPUT_FILE = join(OUTPUT_DIR, "prompts.ts");
const FIXTURES_DIR = join(ROOT, "src", "agents", "fixtures");

const engine = new TemplateEngine();

type PromptRecord = {
  name: string;
  sourcePath: string;
  template: string;
};

type CatalogEntry = Record<string, unknown> & {
  stub?: string;
};

type CatalogManifest = {
  fixtureFilename: string;
  manifestFilename: string;
};

const CATALOG_MANIFESTS: CatalogManifest[] = [
  { fixtureFilename: "agent-catalog.json", manifestFilename: "agent-catalog.manifest.json" },
  { fixtureFilename: "skill-catalog.json", manifestFilename: "skill-catalog.manifest.json" },
];

function loadTemplate(sourcePath: string): string {
  const template = readFileSync(sourcePath, "utf8");
  const validation = engine.validate(template);
  if (!validation.valid) {
    const details = validation.errors
      .map((error) => `${error.message} (${error.line}:${error.column})`)
      .join("; ");
    throw new Error(`Invalid prompt stub ${relative(ROOT, sourcePath)}: ${details}`);
  }
  return template;
}

function loadCatalogStubNames(): Set<string> {
  const stubNames = new Set<string>();

  for (const manifest of CATALOG_MANIFESTS) {
    const manifestPath = join(PROMPTS_DIR, manifest.manifestFilename);
    const entries = JSON.parse(readFileSync(manifestPath, "utf8")) as CatalogEntry[];
    for (const entry of entries) {
      if (typeof entry.stub === "string" && entry.stub.trim()) {
        stubNames.add(entry.stub.trim());
      }
    }
  }

  return stubNames;
}

function loadPromptRecords(excludedStubNames: Set<string>): PromptRecord[] {
  return readdirSync(PROMPTS_DIR, { withFileTypes: true })
    .filter((entry) =>
      entry.isFile()
      && entry.name.endsWith(".stub.md")
      && !excludedStubNames.has(entry.name)
    )
    .map((entry) => {
      const sourcePath = join(PROMPTS_DIR, entry.name);
      return {
        name: entry.name.replace(/\.stub\.md$/u, ""),
        sourcePath,
        template: loadTemplate(sourcePath),
      };
    })
    .sort((left, right) => left.name.localeCompare(right.name));
}

function buildCatalogExport(name: string, typeName: string, entries: CatalogEntry[]): string {
  return [
    `export const ${name} = `,
    `${JSON.stringify(entries, null, 2)} as const;`,
    "",
    `export type ${typeName} = (typeof ${name})[number];`,
    "",
  ].join("\n");
}

function buildOutput(records: PromptRecord[], agentCatalog: CatalogEntry[], skillCatalog: CatalogEntry[]): string {
  const entries = records
    .map((record) => {
      const relPath = relative(ROOT, record.sourcePath).replace(/\\/g, "/");
      return `  ${JSON.stringify(record.name)}: ${JSON.stringify(record.template)}, // ${relPath}`;
    })
    .join("\n");

  return [
    "// Generated by scripts/generate-prompts.ts. Do not edit directly.",
    "",
    "export const PROMPT_TEMPLATES = {",
    entries,
    "} as const;",
    "",
    "export type PromptTemplateName = keyof typeof PROMPT_TEMPLATES;",
    "",
    buildCatalogExport("AGENT_CATALOG", "AgentCatalogBundleEntry", agentCatalog),
    buildCatalogExport("SKILL_CATALOG", "SkillCatalogBundleEntry", skillCatalog),
  ].join("\n");
}

function buildCatalogEntries(manifestFilename: string): { entries: CatalogEntry[]; stubNames: Set<string> } {
  const entries = JSON.parse(readFileSync(join(PROMPTS_DIR, manifestFilename), "utf8")) as CatalogEntry[];
  const stubNames = new Set<string>();
  const resolvedEntries = entries.map((entry) => {
    if (typeof entry.stub !== "string" || !entry.stub.trim()) {
      return entry;
    }

    const stub = entry.stub.trim();
    stubNames.add(stub);
    const sourcePath = join(PROMPTS_DIR, stub);
    const content = loadTemplate(sourcePath);
    const { stub: _stub, ...rest } = entry;
    return { ...rest, content };
  });

  return { entries: resolvedEntries, stubNames };
}

function generateCatalogArtifacts(): {
  agentCatalog: CatalogEntry[];
  skillCatalog: CatalogEntry[];
  stubNames: Set<string>;
} {
  const stubNames = new Set<string>();
  let agentCatalog: CatalogEntry[] = [];
  let skillCatalog: CatalogEntry[] = [];

  for (const manifest of CATALOG_MANIFESTS) {
    const { entries, stubNames: manifestStubNames } = buildCatalogEntries(manifest.manifestFilename);
    for (const name of manifestStubNames) stubNames.add(name);

    writeFileSync(
      join(FIXTURES_DIR, manifest.fixtureFilename),
      `${JSON.stringify(entries, null, 2)}\n`,
      "utf8",
    );

    if (manifest.fixtureFilename === "agent-catalog.json") {
      agentCatalog = entries;
    } else if (manifest.fixtureFilename === "skill-catalog.json") {
      skillCatalog = entries;
    }
  }

  return { agentCatalog, skillCatalog, stubNames };
}

function main(): void {
  const { agentCatalog, skillCatalog, stubNames } = generateCatalogArtifacts();
  const records = loadPromptRecords(stubNames);
  mkdirSync(OUTPUT_DIR, { recursive: true });
  writeFileSync(OUTPUT_FILE, buildOutput(records, agentCatalog, skillCatalog), "utf8");
}

main();
